name: randoeats
description: Your atomic-age appetite assistant
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  intl: ^0.20.2
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#F5F0E1"
  image: assets/images/rand-o-eats.png
  android_12:
    color: "#F5F0E1"
    image: assets/images/rand-o-eats.png
  web: true
  ios: true
  android: true
